#####################################
## common properties
#####################################

zookeeper:
  connectString: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
  maxRetries: 3
  sleepMsBetweenRetries: 100

---

#####################################
## locking
#####################################

spring:
  profiles: locking

