// Code generated by mockery (devel). DO NOT EDIT.

package mockeryexample

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserDB is an autogenerated mock type for the UserDB type
type MockUserDB struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, u
func (_m *MockUserDB) Save(ctx context.Context, u *User) error {
	ret := _m.Called(ctx, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
